platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: perf-test-repo
  - name: bbl-state

outputs:
  - name: integration-config

run:
  path: perf-test-repo/concourse/tasks/generate-config/task.sh

params:
  SYSTEM_DOMAIN:
