platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: cf-performance-tests-pipeline
  - name: bbl-state

outputs:
  - name: integration-config

run:
  path: cf-performance-tests-pipeline/ci/tasks/generate-cats-config/task.sh

params:
  SYSTEM_DOMAIN:
