#!/bin/bash

set -eu
#TODO run shellcheck when done

echo -e "\nInstalling matplotlib..."
pip install matplotlib

if [ -z "$TEST_RESULTS_FOLDER" ]; then
  echo "Task parameter 'TEST_RESULTS_FOLDER' is empty. Check pipeline configuration."
  exit 1
fi
if [ -z "$GENERATED_CHARTS_FOLDER" ]; then
  echo "Task parameter 'GENERATED_CHARTS_FOLDER' is empty. Check pipeline configuration."
  exit 1
fi
mkdir -p "$GENERATED_CHARTS_FOLDER"

echo -e "\nRunning Python script..."
python ./perf-test-repo/concourse/generate_chart.py \
  --test-results "$TEST_RESULTS_FOLDER" --generated-charts "$GENERATED_CHARTS_FOLDER"

echo -e "\nCommitting generated chart..."
# must copy original git repository to the "repository" folder specified in the "put" resource
cp -r "perf-test-repo/." "generated-chart-output/"

echo -e "\n Installing git lfs"
tmpdir="$(mktemp -d git_lfs_install.XXXXXX)"

cd "$tmpdir"
curl -Lo git.tar.gz https://github.com/github/git-lfs/releases/download/v1.1.0/git-lfs-linux-386-1.1.0.tar.gz
gunzip git.tar.gz
tar xf git.tar
mv git-lfs-1.1.0/git-lfs /usr/bin
cd ..
rm -rf "$tmpdir"
git lfs install

pushd "generated-chart-output" > /dev/null
  status="$(git status --porcelain)"
  if [[ -n "$status" ]]; then
    git config user.name "${GIT_COMMIT_USERNAME}"
    git config user.email "${GIT_COMMIT_EMAIL}"
    git add .
    git commit -m "${GIT_COMMIT_MESSAGE}"
  fi
popd > /dev/null

echo "Finished."
