platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
  version:
    digest: sha256:e5a5877fa88caa76b3f8dafe7d15111b295a97506780dfe16cbf1e05a3e4fbad

inputs:
  - name: perf-test-repo
  - name: cf-performance-tests
  - name: bbl-state
  - name: cf-deployment

outputs:
  - name: performance-test-results

run:
  path: perf-test-repo/concourse/tasks/run-performance-tests/task.sh

params:
  GIT_COMMIT_EMAIL: "((cf-perf-github-user-email))"
  GIT_COMMIT_USERNAME: "((cf-perf-github-username))"
  GIT_COMMIT_MESSAGE: "Performance tests results"
  TEST_RESULTS_FOLDER: "perf-test-repo/((test-results-folder))"
  TEST_SUITE_FOLDER: "((test-suite-folder))"
  DATABASE_TYPE: "((database-type))"
